#!/bin/bash

#部署工具
# miwenshu @ 2021.5

NAME=vincentmi/hugo-builder
CONTINER_NAME=${NAME//\//_}
PORT=1313
DIR=$(cd "$(dirname "$0")";pwd)

doHelp() {
    echo ""
    echo "jekyll develop util by vincent_mi"
    echo "   { NAME=${NAME},PORT=${PORT},DIR=${DIR}}   "
    echo " "
    echo "Using : ./build [command1] [command2] ..."
    echo ""
    echo "Commands: "
    echo "  image : pull hugo builder docker images"
    echo "  servdisk : serv hugo in your local server on port 1313"
    echo "  serv : serv hugo in memory on port 1313"
    echo "  build : build hugo pages"
    echo "  index : upload index to algolia"
}

doImage(){
    docker pull -t ${NAME}  ./  
    echo -e "\033[32m image build success \033[0m"
}

doPull(){
    git -C $DIR pull -v
    echo  -e "\033[32m site pull success \033[0m"
}

doServDisk() {
    echo "using ${NAME} , port=${PORT}"

    docker run -it  --rm \
        --name=${CONTINER_NAME}_serv  \
        --volume="$DIR:/app" \
        --publish "${PORT}:1313" \
        ${NAME} \
        hugo server -s /app  --bind 0.0.0.0  --renderToDisk
}

doServMem() {
    echo "using ${NAME} , port=${PORT}"

    docker run -it  --rm \
        --name=${CONTINER_NAME}_serv  \
        --volume="$DIR:/app" \
        --publish "${PORT}:1313" \
        ${NAME} \
        hugo server -s /app  --bind 0.0.0.0  --buildFuture --buildDrafts
}

doBuild(){
    echo "using ${NAME} , dir = ${DIR}"
    docker run  --rm \
        --name=${CONTINER_NAME}_builder  \
        --volume="$DIR:/app" \
        ${NAME} \
        hugo --source /app
     echo -e "\033[32m site build success \033[0m"
}

doIndex() {
    echo "using ${NAME} , dir=${DIR}"
    docker run  --rm \
        --name=${CONTINER_NAME}  \
        --volume="$DIR:/app" \
        ${NAME} \
        pagefind --source public
     echo -e "\033[32m pagefind index success \033[0m"
}

doCommand() {
    if [ "${1}" = "image" ]
    then
        doImage

    elif [ "${1}" = "servdisk" ]
    then
        doServDisk

    elif [ "${1}" = "serv" ]
    then
        doServMem

    elif [ "${1}" = "pull" ]
    then
        doPull

    elif [ "${1}" = "build" ]
    then
        doBuild

    elif [ "${1}" = "index" ]
    then
        doIndex

    fi
}

for i in $*; do
    doCommand $i
done

if [ $# -eq 0 ]
then 
    doHelp
fi

#doCommand ${1}


exit
