#!/bin/bash

#部署工具
# miwenshu @ 2021.5

NAME=vincentmi/jk_vnzmi
CONTINER_NAME=${NAME//\//-}
PORT=4000
DIR=$(cd "$(dirname "$0")";pwd)

doHelp() {
    echo ""
    echo "jekyll develop util by vincent_mi"
    echo "   { NAME=${NAME},PORT=${PORT},DIR=${DIR}}   "
    echo " "
    echo "Using : ./build [command1] [command2] ..."
    echo ""
    echo "Commands: "
    echo "  image : build a custom jekyll builder docker images"
    echo "  serv : serv jekyll in your local server on port 4000"
    echo "  build : build jekyll pages"
    echo "  index : upload index to algolia"
}

doImage(){
    docker build -t ${NAME}  ./  
    echo  "\033[32m image build success \033[0m"
}

doPull(){
    git -C $DIR pull -v
    echo  "\033[32m pull success \033[0m"
}

doServ() {
    echo "using ${NAME} , port=${PORT}"
    docker run -it  --rm \
        --name=${CONTINER_NAME}_serv  \
        --volume="$DIR:/web" \
        --publish "${PORT}:4000" \
        ${NAME} \
        /usr/local/bundle/bin/jekyll serve  --config _config.yml,_config_dev.yml --host 0.0.0.0
}

doBuild(){
    echo "using ${NAME} , dir = ${DIR}"
    docker run  --rm \
        --name=${CONTINER_NAME}_builder  \
        --volume="$DIR:/web" \
        ${NAME} \
        /usr/local/bundle/bin/jekyll build --drafts --future -V
     echo "\033[32m site build success \033[0m"
}

doIndex() {
    echo "using ${NAME} , dir=${DIR}"
    docker run  --rm \
        --name=${CONTINER_NAME}  \
        --volume="$DIR:/web" \
        -e "ALGOLIA_API_KEY=$ALGOLIA_API_KEY" \
        ${NAME} \
        /usr/local/bundle/bin/jekyll algolia
     echo "\033[32m algolia upload success \033[0m"
}

doCommand() {
    if [ "${1}" = "image" ]
    then
        doImage

    elif [ "${1}" = "serv" ]
    then
        doServ

    elif [ "${1}" = "pull" ]
    then
        doPull

    elif [ "${1}" = "build" ]
    then
        doBuild

    elif [ "${1}" = "index" ]
    then
        doIndex

    fi
}

for i in $*; do
    doCommand $i
done

if [ $# -eq 0 ]
then 
    doHelp
fi

#doCommand ${1}


exit
